### ISSUE TITLE
Tweet content incorrect

### ISSUE THREAD

**Issue by tomgreever** [bitovi/canjs.com#117]
See: http://canjs.com/community.html#!twitter
![screen shot 2013-07-31 at 8 36 53 am](https://f.cloud.github.com/assets/326843/886255/58e087d4-f9e6-11e2-8842-898060220aa0.png)

1. The BitHub API probably needs to remove follow events from this content and only show actual tweets (Nik/Vel)

2. The title should be changed to "Tweets about CanJS" or "Recent Twitter Chatter" or something. 

3. We really should add the tweets from the CanJS acct in this pane too, like in a sidebar or something. It's weird that we're showing other ppl's tweets and not our own. This is a design thing for me. (Tom)

**Comment by daffl** [comment]
I think this is fixed as well.
