### ISSUE TITLE
docjs branch - version number displayed underneath tag

### ISSUE THREAD

**Issue by ccummings** [bitovi/canjs.com#223]
On any page that specifies a release version, that version number appears underneath the type tag. Two examples:

http://local.canjs.com/docs/can.events.inserted.html
![image](https://dl.dropboxusercontent.com/u/24216678/Screenshot%202014-10-09%2020.57.03.png)

http://local.canjs.com/docs/can.Component.html
![image](https://dl.dropboxusercontent.com/u/24216678/Screenshot%202014-10-09%2020.57.20.png)

I tested this in Chrome 37 and FF 32 and saw the exact same behavior.

**Comment by daffl** [comment]
Looks like this is solved as well.
