### ISSUE TITLE
canjs.com Bitovi menu incorrect links

### ISSUE THREAD

**Issue by tomgreever** [bitovi/canjs.com#228]
This menu is using the old Bitovi.com nav and links. Should be updated to change Consulting to Development and add Design, change People to About: 
![screen shot 2014-12-10 at 12 39 26 pm](https://cloud.githubusercontent.com/assets/326843/5381719/972da994-8069-11e4-9f01-715371d8eefd.png)

**Comment by daffl** [comment]
This should be fixed now
