### ISSUE TITLE
Docs: v2.2-pre QA - Can Fixture Response Handler Page is not looking correct

### ISSUE THREAD

**Issue by BigAB** [bitovi/canjs.com#232]
/2.2-pre/docs/can.fixture.types.responseHandler.html

Looks off:

2.1
----
![screen shot 2015-01-05 at 2 26 53 am](https://cloud.githubusercontent.com/assets/76821/5611235/a94f607a-9489-11e4-8fa9-3de97dabda03.png)

2.2-pre
----
![screen shot 2015-01-05 at 2 26 44 am](https://cloud.githubusercontent.com/assets/76821/5611234/a9480b22-9489-11e4-9399-1cf53e8c287b.png)

**Comment by justinbmeyer** [comment]
Fixed by https://github.com/bitovi/documentjs/commit/088ce7b77493f678989847e02a27e5eebe1ac238
