### ISSUE TITLE
Documentation for inserted event

### ISSUE THREAD

**Issue by daffl** [bitovi/canjs.com#233]
The documentation for the inserted event is very hard to find (in fact I couldn't find it just quickly looking at the API). We should move it to a better spot.

**Comment by justinbmeyer** [comment]
I agree it's not immediately obvious:

http://canjs.com/docs/can.events.inserted.html

Where would be a better spot?  This is something provided by can.util.  We could bring it "out" of can.util, but it doesn't belong outside of can.util.

**Comment by moschel** [comment]
We should at least link to this from can.Component. 

Also it should link to the removed event.

**Comment by daffl** [comment]
Closed via https://github.com/bitovi/canjs/pull/1673
