### ISSUE TITLE
broken makeFindAll example

### ISSUE THREAD

**Issue by moschel** [bitovi/canjs.com#234]
http://canjs.com/docs/can.Model.makeFindAll.html

![screenshot 2015-02-20 12 10 31](https://cloud.githubusercontent.com/assets/22180/6306475/86d09d7c-b8f9-11e4-9f99-c62485e861b3.png)

**Comment by julia-allyce** [comment]
Looks like this was fixed with this commit:
https://github.com/bitovi/canjs/commit/5be3c68320ac2485a4bb36013b097fbbd754525b
Should be in the new release :smile:
