### ISSUE TITLE
CDN link for jQuery (2.x) points to a file name that doesn't exist (404)

### ISSUE THREAD

**Issue by mjstahl** [bitovi/canjs.com#245]
On `http://canjs.com/download.html` the CDN url for jQuery 2.x points to `(http)//canjs.com/release/2.2.4/can.jquery-2.js` which returns a 404 when attempting to use.

**Comment by mjstahl** [comment]
`https://github.com/bitovi/canjs.com/blob/gh-pages/download.html` does not include a jquery 2.x option for the CDN.  We might just have to redeploy.

**Comment by daffl** [comment]
The links are pulled dynamically from the download builder (`configurations` option from http://bitbuilder.herokuapp.com/canjs). We might have to add a `hidden` flag to jQuery 2.x and update our JS accordingly.

**Comment by daffl** [comment]
jQuery 2.x configuration is now being hidden
