### ISSUE TITLE
can.view.attr - demos not working

### ISSUE THREAD

**Issue by James0x57** [bitovi/canjs.com#246]
Hihi

The demos on this page:
http://canjs.com/docs/can.view.attr.html
are not working.
(the "Demo" tab is blank/white, the js and html tabs are populated as expected)

There are js errors in the console related to steal not being found.

If this issue is easy to fix, please let me know how or point me to the commit/code that does it so I can potentially hop on these when I notice them in the future!

Thank you!
//James

**Comment by justinbmeyer** [comment]
yes, it's an easy fix.  Look at the demo html page, you'll see it is using an older version of steal.  Making it use the right version of steal like all the other demos is all that needs to be done.

**Comment by justinbmeyer** [comment]
attr's md file: https://github.com/bitovi/canjs/blob/master/view/doc/attr.md

You'll notice all the @demo tags.

Those are using steal incorrectly:

https://github.com/bitovi/canjs/blob/master/view/doc/dynamic_tooltip.html#L47


@matthewp you'll notice it's trying to do a CORS request for jQueryUI.

This will have to be worked around.

**Comment by daffl** [comment]
Fixed via https://github.com/bitovi/canjs/pull/1672
