### ISSUE TITLE
Add bithub

### ISSUE THREAD

**Issue by moschel** [bitovi/canjs.com#251]
add the bithub widget somewhere on the homepage

**Comment by moschel** [comment]
use bithub@bitovi.com and bitovi1337$
that account is on unlimited plan
and you can add as many hubs as needed, this one already hosts the steal hub

**Comment by marshallswain** [comment]
@tomgreever Do you have a recommendation on where you'd like to see this?

![screen shot 2015-05-11 at 9 11 35 pm](https://cloud.githubusercontent.com/assets/128857/7579521/65f3a06e-f822-11e4-981b-a7ff3815f28a.png)

**Comment by tomgreever** [comment]
Yes that's a good spot. Thanks!
